apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
stringData:
  rootUser: REPLACE_ME
  rootPassword: REPLACE_ME
  oidcClientId: minio
  oidcClientSecret: REPLACE_ME
